Add all typescript types for web-js
sulu/web-js pull request #68
Opened 2022-01-25 18:14 UTC by mfehr94

2022-01-25 21:18 UTC, alexander-schranz requested changes
@mfehr94 Thx for the pull request. I think in some files the jsdocs is missing and so some `any` was added to some methods. We should where possible fix the jsdocs and update the typescript types. Also analyse why some `.d.ts` seems to have some methods or props just missing.

2022-01-25 21:18 UTC, alexander-schranz commented on tsconfig.json
> +  }
```suggestion
{
    "include": ["packages/**/*"],
    "compilerOptions": {
        "allowJs": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "outDir": "types",
        "declarationMap": true
    }
}
```

2022-01-25 21:18 UTC, alexander-schranz commented on types/components/expand/expand.d.ts
> +    initialize: (el: HTMLElement, options: object) => void;
Is there a way we can provide a interface for this? So we don't need declare this over again?

2022-01-25 21:18 UTC, alexander-schranz commented on types/services/api/api.d.ts
> +export declare function get(uri: any, data: any): Promise<any>;
uri: any looks false, same for data: any

2022-01-25 21:18 UTC, alexander-schranz commented on types/experimental/lazy/lazy.d.ts
> +export const registerComponent: any;
this looks weird?

Why looks this different then the core.js?

2022-01-25 21:18 UTC, alexander-schranz commented on types/core/core.d.ts
> +import registerComponent = web.registerComponent;
Does typescript correctly read the types from jsdocs here? 

https://github.com/sulu/web-js/blob/49f6e9e6a173b92455402a6d8a6383e488942a2f/packages/core/core.js#L184-L186

So it will correctly fail if it is called with something else?

2022-01-25 21:18 UTC, alexander-schranz commented on types/components/accordion/accordion.d.ts
> +//# sourceMappingURL=accordion.d.ts.map
Do we need the map files?

2022-01-25 21:18 UTC, alexander-schranz commented on types/components/accordion/accordion.d.ts.map
> +{"version":3,"file":"accordion.d.ts","sourceRoot":"","sources":["../../../packages/components/accordion/accordion.js"],"names":[],"mappings":"AAIiB;qBAsCF,WAAW,WACX,MAAM;EA0EpB"}
Are this files required?

2022-01-25 21:18 UTC, alexander-schranz commented on types/services/google-map-library/google-map-library.d.ts
> +export const promise: any;
For me looks here are all methods missing.

2022-01-26 10:13 UTC, mfehr94 commented
@alexander-schranz thank you for the first review and the suggestions. This are autogenerated types from typescript compiler and just a quick starting point for me to work on. I will check the JSCodes and try to fix them, also adding the missing props and methods as soon as possible.

2022-01-26 10:15 UTC, mfehr94 commented on types/components/accordion/accordion.d.ts.map
> +{"version":3,"file":"accordion.d.ts","sourceRoot":"","sources":["../../../packages/components/accordion/accordion.js"],"names":[],"mappings":"AAIiB;qBAsCF,WAAW,WACX,MAAM;EA0EpB"}
@alexander-schranz if you want to provide autocomplitons for IDE yes, if not it can be disabled with `"declarationMap": false`

2022-01-26 10:15 UTC, mfehr94 commented on types/components/accordion/accordion.d.ts
> +//# sourceMappingURL=accordion.d.ts.map
@alexander-schranz if you want to provide autocomplitons for IDE yes, if not it can be disabled with `"declarationMap": false`

2022-01-29 14:22 UTC, alexander-schranz commented
@mfehr94 Do we even need the `.ts` files if we provide all type information over JSDocs: https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html ?

2022-01-29 14:29 UTC, mfehr94 commented
@alexander-schranz good possible, I must test that and add the missing JSDocs. At the moment type script don't like the important of the web in custom J's components in my test project.

2022-05-07 14:49 UTC, mario-fehr commented on types/experimental/lazy/lazy.d.ts
> +export const registerComponent: any;
Because of this declaration:
 ```js
 var lazy = {
        componentRegistry: {},
        serviceRegistry: {},
        deferredComponents: {},
        deferredServices: {},
    };```

2022-05-07 15:58 UTC, alexander-schranz commented on packages/experimental/lazy/lazy.js
> +    var lazy = {};
```suggestion
    var lazy = {
        componentRegistry: {},
        serviceRegistry: {},
        deferredComponents: {},
        deferredServices: {},
    };
```

This object should stay as before.

2023-09-21 10:53 UTC, closed without merging